import 'package:get/get.dart';

class Localization extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'locale': 'en_US',
          'home': 'Home',
          'weather': 'Weather',
          'calendar': 'Calendar',
          'settings': 'Settings',
          'change_language': 'Language',
          'product': 'Products',
          'chemicals': 'Chemicals',
          'fertilizer': 'Fertilizer',
          'seed': 'Seed',
          'fuel': 'Fuel',
          'new_event': 'New task',
          'enter_event': 'Enter task',
          'cancel': 'Cancel',
          'add': 'Add',
          'please_enter_event': 'Please enter task.',
          'done': 'Done.',
          'edit': 'Edit task',
          'edit1': 'Edit',
          'edited': 'Edited.',
          'today_tasks': 'Today tasks',
          'not_task': 'Not tasks today',
          'name': 'Name',
          'quantity': 'Quantity',
          'accept':'Accept',
          'kg': ' kg',
          'l': ' L'
        },
        'ru_RUS': {
          'locale': 'ru_RU',
          'home': 'Главная страница',
          'weather': 'Погода',
          'calendar': 'Календарь',
          'settings': 'Настройки',
          'change_language': 'Язык',
          'product': 'Материалы',
          'chemicals': 'Химикаты',
          'fertilizer': 'Удобрения',
          'seed': 'Семена',
          'fuel': 'Топливо',
          'new_event': 'Новое задание',
          'enter_event': 'Введите задание',
          'cancel': 'Отмена',
          'add': 'Добавить',
          'please_enter_event': 'Пожалуйста введите задание.',
          'done': 'Выполнено.',
          'edit': 'Изменить задание',
          'edit1': 'Изменить',
          'edited': 'Изменено.',
          'today_tasks': 'Сегодняшние задачи',
          'not_task': 'Нет заданий на сегодня',
          'name': 'Название',
          'quantity': 'Количество',
          'accept': 'Принять',
          'kg': ' кг',
          'l': ' л',
        }
      };
}
